baseURL = 'https://masonfulp.github.io/the-fixer/'
languageCode = 'en-us'
title = 'The Fixer'
theme = 'PaperMod'

[params]
  defaultTheme = 'auto'
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  
  # ADSENSE PREP (Fill this later)
  # googleAdsense = "ca-pub-XXXXXXXXXXXXXXXX"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Fixes"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 20
